"""empty message

Revision ID: 049139dd64ac
Revises: 4518e8caa6e5
Create Date: 2023-02-02 00:33:16.679180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049139dd64ac'
down_revision = '4518e8caa6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Itinerarys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Itinerarys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Itinerarys_itinerary'), ['itinerary'], unique=False)

    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_index('ix_destination_destination')

    op.drop_table('destination')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('destination', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('start', sa.TIME(), nullable=True),
    sa.Column('end', sa.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.create_index('ix_destination_destination', ['destination'], unique=False)

    with op.batch_alter_table('Itinerarys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Itinerarys_itinerary'))

    op.drop_table('Itinerarys')
    # ### end Alembic commands ###
